# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kyle Hendershot
tagline:             'Actor, Model, Entrepeneur'
description:         'Paul Hendricks is a Actor, Model, Entrepeneur based out of Los Angeles, California.'
url:                 http://kylehendershot.com
baseurl:             'http://kylehendershot.com'
paginate:            5

# About/contact
author:
  name:              Kyle Hendershot
  url:               http://kylehendershot.com
  email:             hendershotbooking@gmail.com

# Custom vars
version:             1.0.0
