# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kyle Hendershot
tagline:             'Actor & Writer'
description:         'Kyle Hendershot is an Actor and Writer from Ohio now living in Los Angeles, CA. '
url:                 http://kylehendershot.com
baseurl:             'http://kylehendershot.com'
paginate:            5

# About/contact
author:
  name:              Kyle Hendershot
  url:               http://kylehendershot.com
  email:             hendershotbooking@gmail.com

# Custom vars
version:             1.0.0
