# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'TO BE EDITED'
description:         'to be edited'
url:                 http://paulhendricks.io
baseurl:             'http://paulhendricks.io'
paginate:            5

# About/contact
author:
  name:              Paul Hendricks
  url:               http://paulhendricks.io
  email:             paul.hendricks.2013@owu.edu

# Custom vars
version:             1.0.0
